[project]
name = "case1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.7"
dependencies = [
    "fastapi>=0.121.2",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.38.0",
]
